/* ─────────────────────────────────────────────────────────────────────────
   Opportunity Mock Data
   Sample opportunities for the Sales Funnel module
   ───────────────────────────────────────────────────────────────────────── */

const STAGES = [
  { name: 'Prospecting', probability: 10 },
  { name: 'Qualification', probability: 20 },
  { name: 'Needs Analysis', probability: 30 },
  { name: 'Value Proposition', probability: 50 },
  { name: 'Proposal / Price Quote', probability: 65 },
  { name: 'Negotiation / Review', probability: 80 },
  { name: 'Closed Won', probability: 100 },
  { name: 'Closed Lost', probability: 0 },
];

const OPPORTUNITIES = [
  {
    id: 'opp-001',
    name: 'Acme Corp — Q3 Expansion Deal',
    accountId: 'acc-001',
    accountName: 'Acme Corporation',
    contactId: 'con-001',
    contactName: 'Sarah Lin',
    closeDate: '2026-09-30',
    stageName: 'Negotiation / Review',
    probability: 80,
    amount: 48500,
    expectedRevenue: 38800,
    type: 'New Business',
    leadSource: 'Referral',
    description: 'Enterprise HVAC system upgrade for manufacturing facility',
    nextStep: 'Send revised proposal by Friday — follow up with procurement team Monday AM',
    isPrivate: false,
    isPriorityRecord: true,
    isClosed: false,
    isWon: false,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Commit',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-10T14:30:00Z',
    createdBy: 'user-001',
    ownerId: 'user-001',
    ownerName: 'James K.',
    lastStageChangeDate: '2026-06-08T09:00:00Z',
    lastActivityDate: '2026-06-10T14:30:00Z',
    syncedQuoteId: 'qt-001',
  },
  {
    id: 'opp-002',
    name: 'TechGlobal — Annual Maintenance Contract',
    accountId: 'acc-002',
    accountName: 'TechGlobal Solutions',
    contactId: 'con-002',
    contactName: 'Michael Chen',
    closeDate: '2026-08-15',
    stageName: 'Proposal / Price Quote',
    probability: 65,
    amount: 125000,
    expectedRevenue: 81250,
    type: 'Renewal',
    leadSource: 'Event',
    description: 'Annual preventive maintenance and support contract renewal',
    nextStep: 'Schedule follow-up meeting with VP of Operations',
    isPrivate: false,
    isPriorityRecord: false,
    isClosed: false,
    isWon: false,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Best Case',
    createdAt: '2026-05-15T10:30:00Z',
    updatedAt: '2026-06-05T16:45:00Z',
    createdBy: 'user-002',
    ownerId: 'user-002',
    ownerName: 'Lisa M.',
    lastStageChangeDate: '2026-06-01T11:00:00Z',
    lastActivityDate: '2026-06-05T16:45:00Z',
    syncedQuoteId: null,
  },
  {
    id: 'opp-003',
    name: 'Metro Hospital — Equipment Installation',
    accountId: 'acc-003',
    accountName: 'Metro Healthcare Network',
    contactId: 'con-003',
    contactName: 'Dr. Robert Williams',
    closeDate: '2026-07-31',
    stageName: 'Needs Analysis',
    probability: 30,
    amount: 275000,
    expectedRevenue: 82500,
    type: 'New Business',
    leadSource: 'Web',
    description: 'Complete HVAC system installation for new hospital wing',
    nextStep: 'Conduct site survey and submit technical specifications',
    isPrivate: false,
    isPriorityRecord: true,
    isClosed: false,
    isWon: false,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Pipeline',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-12T10:15:00Z',
    createdBy: 'user-001',
    ownerId: 'user-001',
    ownerName: 'James K.',
    lastStageChangeDate: '2026-06-10T14:00:00Z',
    lastActivityDate: '2026-06-12T10:15:00Z',
    syncedQuoteId: null,
  },
  {
    id: 'opp-004',
    name: 'Pacific Manufacturing — Production Line Automation',
    accountId: 'acc-004',
    accountName: 'Pacific Manufacturing Co.',
    contactId: 'con-004',
    contactName: 'Jennifer Park',
    closeDate: '2026-10-30',
    stageName: 'Qualification',
    probability: 20,
    amount: 450000,
    expectedRevenue: 90000,
    type: 'New Business',
    leadSource: 'Cold Call',
    description: 'Automated production line HVAC control system',
    nextStep: 'Budget and authority verification meeting',
    isPrivate: false,
    isPriorityRecord: false,
    isClosed: false,
    isWon: false,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Pipeline',
    createdAt: '2026-06-08T11:30:00Z',
    updatedAt: '2026-06-12T09:30:00Z',
    createdBy: 'user-003',
    ownerId: 'user-003',
    ownerName: 'David R.',
    lastStageChangeDate: '2026-06-10T15:30:00Z',
    lastActivityDate: '2026-06-12T09:30:00Z',
    syncedQuoteId: null,
  },
  {
    id: 'opp-005',
    name: 'Green Energy — Solar Integration Project',
    accountId: 'acc-005',
    accountName: 'Green Energy Systems',
    contactId: 'con-005',
    contactName: 'Thomas Green',
    closeDate: '2026-09-15',
    stageName: 'Closed Won',
    probability: 100,
    amount: 189000,
    expectedRevenue: 189000,
    type: 'New Business',
    leadSource: 'Referral',
    description: 'Solar-powered HVAC control system integration',
    nextStep: 'Project kickoff meeting scheduled',
    isPrivate: false,
    isPriorityRecord: false,
    isClosed: true,
    isWon: true,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Closed',
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-06-10T16:00:00Z',
    createdBy: 'user-002',
    ownerId: 'user-002',
    ownerName: 'Lisa M.',
    lastStageChangeDate: '2026-06-10T16:00:00Z',
    lastActivityDate: '2026-06-10T16:00:00Z',
    syncedQuoteId: 'qt-002',
  },
  {
    id: 'opp-006',
    name: 'Industrial Solutions — Maintenance Contract',
    accountId: 'acc-006',
    accountName: 'Industrial Solutions Ltd.',
    contactId: 'con-006',
    contactName: 'Mark Thompson',
    closeDate: '2026-05-31',
    stageName: 'Closed Lost',
    probability: 0,
    amount: 85000,
    expectedRevenue: 0,
    type: 'Renewal',
    leadSource: 'Web',
    description: 'Annual maintenance contract renewal - lost to competitor',
    nextStep: '',
    isPrivate: false,
    isPriorityRecord: false,
    isClosed: true,
    isWon: false,
    currencyIsoCode: 'USD',
    forecastCategoryName: 'Closed',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-05-28T14:00:00Z',
    createdBy: 'user-001',
    ownerId: 'user-001',
    ownerName: 'James K.',
    lastStageChangeDate: '2026-05-28T14:00:00Z',
    lastActivityDate: '2026-05-28T14:00:00Z',
    syncedQuoteId: null,
  },
];

export function getOpportunityById(id) {
  return OPPORTUNITIES.find(o => o.id === id);
}

export function getOpportunities() {
  return OPPORTUNITIES;
}

export function getOpportunitiesByStage(stageName) {
  return OPPORTUNITIES.filter(o => o.stageName === stageName);
}

export function getOpportunitiesByAccount(accountId) {
  return OPPORTUNITIES.filter(o => o.accountId === accountId);
}

export { STAGES };
