// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UT.ServiceConsole.API.Data;

#nullable disable

namespace UT.ServiceConsole.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528065857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerSupportType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            AccountName = "PUTRA PERKASA ABADI",
                            City = "Palembang",
                            Country = "Indonesia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerSupportType = "Dedicated Customer",
                            Email = "contact@putraabadi.co.id",
                            Industry = "MNG",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-711-12345",
                            Status = "Active"
                        },
                        new
                        {
                            AccountID = 2,
                            AccountName = "SIMS JAYA KALTIM",
                            City = "Samarinda",
                            Country = "Indonesia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerSupportType = "Standard",
                            Email = "info@simskaltim.co.id",
                            Industry = "MNG",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-541-98765",
                            Status = "Active"
                        },
                        new
                        {
                            AccountID = 3,
                            AccountName = "PT. UNITED TRACTORS",
                            City = "Jakarta",
                            Country = "Indonesia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerSupportType = "Premium",
                            Email = "utgroup@unitedtractors.com",
                            Industry = "EQP",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-21-5555555",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentUoM")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("InWarranty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MeasuringDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SMR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetID");

                    b.HasIndex("AccountID");

                    b.HasIndex("EquipmentNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetID = 1,
                            AccountID = 1,
                            AssetName = "GD-829 Komatsu D85ESS-2",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentNumber = "232656",
                            EquipmentUoM = "hm",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Site B - Pit 4",
                            MaterialNumber = "GD825A-2/S3",
                            Plant = "TJE",
                            SMR = 14250.0m,
                            SerialNumber = "13405",
                            ServiceArea = "Tanjung Enim PPA",
                            Status = "Active",
                            UnitCode = "GD-829",
                            UnitModel = "Komatsu D85ESS-2"
                        },
                        new
                        {
                            AssetID = 2,
                            AccountID = 1,
                            AssetName = "GD-830 PC2000 Excavator",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentUoM = "hm",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Site A - Loading Area",
                            MaterialNumber = "PC2000-8",
                            Plant = "TJE",
                            SMR = 12500.0m,
                            SerialNumber = "13406",
                            ServiceArea = "Tanjung Enim PPA",
                            Status = "Active",
                            UnitCode = "GD-830",
                            UnitModel = "Komatsu PC2000"
                        },
                        new
                        {
                            AssetID = 3,
                            AccountID = 2,
                            AssetName = "GD-831 HD785 Truck",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentNumber = "232657",
                            EquipmentUoM = "km",
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Transportation",
                            MaterialNumber = "HD785-7",
                            Plant = "TJE",
                            SMR = 16750.0m,
                            SerialNumber = "13407",
                            ServiceArea = "Tanjung Enim PPA",
                            Status = "Active",
                            UnitCode = "GD-831",
                            UnitModel = "Komatsu HD785"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.HasIndex("ActionType");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("EntityID");

                    b.HasIndex("EntityName");

                    b.HasIndex("EntityName", "EntityID", "ChangedDate");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Case", b =>
                {
                    b.Property<int>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssetID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedOwnerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ComplianceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ContactID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SLABreached")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetResolutionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CaseID");

                    b.HasIndex("AccountID");

                    b.HasIndex("AssetID");

                    b.HasIndex("AssignedOwnerID");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CaseType");

                    b.HasIndex("ContactID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("AssignedOwnerID", "Status");

                    b.HasIndex("Status", "CreatedDate");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            CaseID = 1,
                            AccountID = 1,
                            AssetID = 1,
                            AssignedOwnerID = 2,
                            CaseNumber = "CASE-20260526-00101",
                            CaseType = "Request",
                            ContactID = 1,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            Description = "Operator reported significant hydraulic fluid leakage near right cylinder. Equipment grounded pending repair.",
                            LastModifiedDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            SLABreached = false,
                            StartDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Subject = "Hydraulic Leak on Right Cylinder"
                        },
                        new
                        {
                            CaseID = 2,
                            AccountID = 1,
                            AssetID = 2,
                            AssignedOwnerID = 2,
                            CaseNumber = "CASE-20260525-00100",
                            CaseType = "Incident",
                            ContactID = 1,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unit GD-830 experiencing elevated coolant temperatures. Initial diagnostics show potential radiator blockage or fan malfunction.",
                            LastModifiedDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            SLABreached = false,
                            StartDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = "Assigned",
                            Subject = "Engine Overheating Issue"
                        },
                        new
                        {
                            CaseID = 3,
                            AccountID = 2,
                            AssetID = 3,
                            AssignedOwnerID = 4,
                            CaseNumber = "CASE-20260524-00099",
                            CaseType = "Problem",
                            ContactID = 3,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete transmission failure reported during operation. Unit HD785 unable to shift gears. Requires major overhaul or replacement.",
                            LastModifiedDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Critical",
                            SLABreached = false,
                            StartDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Subject = "Transmission Failure GD-831"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.CaseNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NoteID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("CaseNotes");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ContactID");

                    b.HasIndex("AccountID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactID = 1,
                            AccountID = 1,
                            ContactName = "Andi Wijaya",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Email = "andi@putraabadi.co.id",
                            IsPrimary = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-811-111-2222",
                            Status = "Active",
                            Title = "Operations Manager"
                        },
                        new
                        {
                            ContactID = 2,
                            AccountID = 1,
                            ContactName = "Rini Kartika",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Maintenance",
                            Email = "rini@putraabadi.co.id",
                            IsPrimary = false,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-811-333-4444",
                            Status = "Active",
                            Title = "Technical Lead"
                        },
                        new
                        {
                            ContactID = 3,
                            AccountID = 2,
                            ContactName = "Burhan",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Fleet",
                            Email = "burhan@simskaltim.co.id",
                            IsPrimary = true,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+62-811-555-6666",
                            Status = "Active",
                            Title = "Fleet Manager"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.LoginHistory", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginID");

                    b.HasIndex("LoginDate");

                    b.HasIndex("Success");

                    b.HasIndex("UserID");

                    b.HasIndex("UserID", "LoginDate");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionID");

                    b.HasIndex("Module");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System Administrator",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Case Manager / Supervisor",
                            IsActive = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleID = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Service Advisor / Case Creator",
                            IsActive = true,
                            RoleName = "ServiceAdvisor"
                        },
                        new
                        {
                            RoleID = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Field Mechanic / Technician",
                            IsActive = true,
                            RoleName = "Mechanic"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.SLA", b =>
                {
                    b.Property<int>("SLAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BreachedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SLAType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SLAID");

                    b.HasIndex("CaseID");

                    b.HasIndex("IsBreached");

                    b.HasIndex("SLAType");

                    b.HasIndex("TargetDate");

                    b.ToTable("SLA");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin@utconsole.com",
                            FailedLoginAttempts = 0,
                            FirstName = "System",
                            IsActive = true,
                            IsLockedOut = false,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Administrator",
                            PasswordHash = "gcejzwBoRT2kxdzOWnUL5g==:7TC+3QKZOL8eb+fRgWpd/RsO5WWfd19Q7xtCsa4St0M=",
                            PhoneNumber = "+62811234567",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Email = "john.doe@utconsole.com",
                            FailedLoginAttempts = 0,
                            FirstName = "John",
                            IsActive = true,
                            IsLockedOut = false,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            PasswordHash = "6cTTHQsdQMLvMo30T+/+wA==:lgHCvg4voUl8n3m+cz1PNPz7yzC1wdUniNci1Sb5JgU=",
                            PhoneNumber = "+62811234568",
                            Role = "ServiceAdvisor",
                            Username = "john.doe"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Field Services",
                            Email = "budi.santoso@utconsole.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Budi",
                            IsActive = true,
                            IsLockedOut = false,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Santoso",
                            PasswordHash = "4AdLiqMOn4H2zfXihG5bzg==:kDbPFwW9bAKK3dCaV9R7GcOdc6GzfnGPr144RRJ/iNM=",
                            PhoneNumber = "+62811234569",
                            Role = "Mechanic",
                            Username = "budi.santoso"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Email = "manager.user@utconsole.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Manager",
                            IsActive = true,
                            IsLockedOut = false,
                            LastModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            PasswordHash = "KG/VKYH1/sj0tUdDghMJkA==:VwVMqkzhMc+PXoJz8lP4GFQK0ZZQfATFliVLQS6nfDA=",
                            PhoneNumber = "+62811234570",
                            Role = "Manager",
                            Username = "manager.user"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ABRFileDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualSMR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssetID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedMechanicID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakdownIndicator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastSMR")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("MalfunctionEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MalfunctionStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectPart")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plant")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SAPWorkOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificObjectPart")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TSRDataScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TSRMonitoringScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TSRRootCauseScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkCenter")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkOrderID");

                    b.HasIndex("AccountID");

                    b.HasIndex("AssetID");

                    b.HasIndex("AssignedMechanicID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("OwnerID");

                    b.HasIndex("Status");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.HasIndex("AssignedMechanicID", "Status");

                    b.HasIndex("Status", "CreatedDate");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WorkOrderID = 1,
                            AccountID = 1,
                            AssetID = 1,
                            AssignedMechanicID = 3,
                            BreakdownIndicator = false,
                            CaseID = 1,
                            ContactID = 1,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            Description = "Replace hydraulic cylinder seal and hose assembly. Check fluid level and top up if necessary.",
                            EndDate = new DateTime(2026, 5, 27, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            LastSMR = 14250.0m,
                            OwnerID = 2,
                            Plant = "TJE",
                            StartDate = new DateTime(2026, 5, 26, 7, 31, 0, 0, DateTimeKind.Unspecified),
                            Status = "New",
                            Subject = "Hydraulic System Repair - GD-829",
                            TSRDataScore = 0,
                            TSRMonitoringScore = 0,
                            TSRRootCauseScore = 0,
                            WorkCenter = "FM-TJEPA",
                            WorkOrderNumber = "WO-20260526-00101"
                        },
                        new
                        {
                            WorkOrderID = 2,
                            AccountID = 1,
                            AssetID = 2,
                            AssignedMechanicID = 3,
                            BreakdownIndicator = false,
                            CaseID = 2,
                            ContactID = 1,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Inspect radiator, fans, and coolant system. Perform flush if blockage found. Test thermostat operation.",
                            EndDate = new DateTime(2026, 5, 26, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            LastSMR = 12500.0m,
                            OwnerID = 2,
                            Plant = "TJE",
                            StartDate = new DateTime(2026, 5, 25, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Subject = "Engine Cooling System Diagnosis - GD-830",
                            TSRDataScore = 0,
                            TSRMonitoringScore = 0,
                            TSRRootCauseScore = 0,
                            WorkCenter = "FM-TJEPA",
                            WorkOrderNumber = "WO-20260525-00100"
                        },
                        new
                        {
                            WorkOrderID = 3,
                            AccountID = 2,
                            AssetID = 3,
                            AssignedMechanicID = 3,
                            BreakdownIndicator = false,
                            CaseID = 3,
                            ContactID = 3,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete transmission tear-down and inspection. Identify failed components and plan replacement strategy.",
                            EndDate = new DateTime(2026, 5, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LastModifiedDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSMR = 16750.0m,
                            OwnerID = 4,
                            Plant = "KTM",
                            StartDate = new DateTime(2026, 5, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Subject = "Transmission Overhaul - GD-831",
                            TSRDataScore = 0,
                            TSRMonitoringScore = 0,
                            TSRRootCauseScore = 0,
                            WorkCenter = "FM-KALTIM",
                            WorkOrderNumber = "WO-20260524-00099"
                        });
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.WorkOrderNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkOrderID")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkOrderID");

                    b.ToTable("WorkOrderNotes");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Asset", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Account", "Account")
                        .WithMany("Assets")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Case", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Account", "Account")
                        .WithMany("Cases")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "AssignedOwner")
                        .WithMany()
                        .HasForeignKey("AssignedOwnerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("AssignedOwner");

                    b.Navigation("Contact");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.CaseNote", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Case", "Case")
                        .WithMany("Notes")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Contact", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Account", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.LoginHistory", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.SLA", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Case", "Case")
                        .WithMany("SLAs")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.User", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.WorkOrder", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "AssignedMechanic")
                        .WithMany()
                        .HasForeignKey("AssignedMechanicID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.Case", "Case")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("AssignedMechanic");

                    b.Navigation("Case");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.WorkOrderNote", b =>
                {
                    b.HasOne("UT.ServiceConsole.API.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UT.ServiceConsole.API.Models.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Notes")
                        .HasForeignKey("WorkOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Account", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Cases");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Case", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("SLAs");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.User", b =>
                {
                    b.Navigation("LoginHistories");
                });

            modelBuilder.Entity("UT.ServiceConsole.API.Models.Entities.WorkOrder", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
